# Streamlit Secrets Configuration
# Add your API keys here - DO NOT commit this file to version control

[openai]
api_key = "your-openai-api-key-here"

[elevenlabs]
api_key = "your-elevenlabs-api-key-here"

[cartesia]
api_key = "your-cartesia-api-key-here"

[azure]
speech_key = "your-azure-speech-key-here"
speech_region = "your-azure-region-here"

[datastax]
api_endpoint = "your-datastax-endpoint-here"
api_key = "your-datastax-api-key-here"
keyspace = "your-keyspace-name-here"

# Example with actual structure:
# [openai]
# api_key = "sk-..."
# 
# [elevenlabs]
# api_key = "el_..."
# 
# [cartesia]
# api_key = "cart_..."
# 
# [azure]
# speech_key = "abcd1234..."
# speech_region = "eastus"
# 
# [datastax]
# api_endpoint = "https://your-db-id-region.apps.astra.datastax.com"
# api_key = "AstraCS:..."
# keyspace = "fortigate_kb"